name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Build binaries
        run: |
          # Build for Linux AMD64
          GOOS=linux GOARCH=amd64 go build -o prayers-linux-amd64 ./main.go

          # Build for Linux ARM64
          GOOS=linux GOARCH=arm64 go build -o prayers-linux-arm64 ./main.go

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            prayers-linux-amd64
            prayers-linux-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Publish:
    runs-on: ubuntu-latest
    needs: [Release]
    steps:
      - uses: actions/checkout@v4

      - name: Generate PKGBUILD
        uses: fuad-daoud/release-aur@v1
        with:
          cli_name: "prayers"
          maintainers: "Fuad Daoud <aur@fuad-daoud.com>"
          pkgname: "prayers-bin"
          version: ${{ github.event.release.tag_name }}
          description: "TUI application to display Islamic prayer times based on your location"
          url: "https://github.com/${{ github.repository }}"
          arch: "x86_64,aarch64"
          licence: "MIT"
          source_x86_64: "https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/prayers-linux-amd64"
          source_aarch64: "https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/prayers-linux-arm64"

      - name: Upload PKGBUILD
        uses: actions/upload-artifact@v4
        with:
          name: pkgbuild
          path: output/PKGBUILD

      - name: Publish pkgmate-bin to the AUR
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgname: pkgmate-bin
          pkgbuild: output/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: ${{ github.ref_name }}
          updpkgsums: "true"
